package id.web.izs.sshclient

import id.web.izs.sshclient.core.config.RawConfigStore
import id.web.izs.sshclient.core.config.StoredVault
import id.web.izs.sshclient.core.vault.VaultCrypto
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.int
import org.junit.Assert.*
import org.junit.Test

/**
 * Desktop interop: decrypt a vault blob produced by Node running the EXACT
 * desktop encryptVault (tabby-core vault.service.ts), then run it through the
 * production decrypt path (decrypt -> jsonToRaw -> toDomain).
 *
 * Fixture: app/src/test/resources/desktop-vault.json, generated by
 * /tmp/opencode/make-desktop-vault.cjs (node crypto.pbkdf2Sync 100k/sha512 +
 * aes-256-cbc, JSON.stringify payload — line-for-line desktop replica).
 * Regenerate with: node /tmp/opencode/make-desktop-vault.cjs
 *   app/src/test/resources/desktop-vault.json
 */
class DesktopVaultInteropTest {

    private fun fixture(): JsonObject {
        val loader = requireNotNull(javaClass.classLoader)
        val text = loader.getResourceAsStream("desktop-vault.json")!!.bufferedReader().readText()
        return Json.parseToJsonElement(text) as JsonObject
    }

    @Test
    fun `decrypts a real desktop blob with byte-exact payload`() {
        val f = fixture()
        val s = f["stored"] as JsonObject
        fun str(o: JsonObject, k: String) = (o[k] as kotlinx.serialization.json.JsonPrimitive).content
        val vault = StoredVault(
            version = (s["version"] as kotlinx.serialization.json.JsonPrimitive).int,
            contents = str(s, "contents"),
            keySalt = str(s, "keySalt"),
            iv = str(s, "iv"),
        )
        val pass = str(f, "passphrase")
        val (configJson, secretsJson) = VaultCrypto.decrypt(vault, pass)
        // Byte-exact: the splitter must return desktop's JSON.stringify output verbatim.
        assertEquals(Json.parseToJsonElement((f["expectedConfig"]).toString()), Json.parseToJsonElement(configJson))
        assertEquals(Json.parseToJsonElement((f["expectedSecrets"]).toString()), Json.parseToJsonElement(secretsJson))
        assertEquals(6, (Json.parseToJsonElement(secretsJson) as JsonArray).size)
    }

    @Test
    fun `decrypted desktop config yields every ssh profile`() {
        val f = fixture()
        val s = f["stored"] as JsonObject
        fun str(o: JsonObject, k: String) = (o[k] as kotlinx.serialization.json.JsonPrimitive).content
        val vault = StoredVault(
            version = 1,
            contents = str(s, "contents"),
            keySalt = str(s, "keySalt"),
            iv = str(s, "iv"),
        )
        val (configJson, _) = VaultCrypto.decrypt(vault, str(f, "passphrase"))
        val domain = RawConfigStore.toDomain(RawConfigStore.jsonToRaw(configJson))
        // 4 raw profiles: 3 ssh (one id-less -> minted) + 1 serial (listed, ssh-gated).
        val names = domain.profiles.map { it.name }.toSet()
        assertTrue(names.contains("web-01"))
        assertTrue(names.contains("t\u00ebst-s\u00e9rver \"secrets\" \\ {braces}"))
        assertTrue(names.contains("legacy-no-id"))
        assertTrue(names.contains("console"))
        assertEquals(4, domain.profiles.size)
        assertEquals(3, domain.profiles.count { it.type == "ssh" })
        val web = domain.profiles.find { it.name == "web-01" }!!
        assertEquals("10.0.0.1", web.options.host)
        assertEquals("g-servers", web.group)
        assertEquals("ssh:bbb-222", web.options.jumpHost)
        assertEquals(listOf("vault://file-key-1"), web.options.privateKeys)
        val legacy = domain.profiles.find { it.name == "legacy-no-id" }!!
        assertTrue(legacy.id.startsWith("ssh:custom:"))
        // Groups incl. nesting survive the decrypt path.
        assertEquals(2, domain.groups.size)
        assertEquals("g-servers", domain.groups.find { it.name == "Nested" }?.parentGroupId)
        // Non-ssh config sections round-trip through the blob untouched.
        assertEquals(true, domain.ssh.verifyHostKeys)
    }

    @Test
    fun `live store dump shows everything like desktop readRaw`() {
        val f = fixture()
        val s = f["stored"] as JsonObject
        fun str(o: JsonObject, k: String) = (o[k] as JsonPrimitive).content
        val vault = StoredVault(1, str(s, "contents"), str(s, "keySalt"), str(s, "iv"))
        val (configJson, _) = VaultCrypto.decrypt(vault, str(f, "passphrase"))
        // Same merge decryptToLoaded builds for Loaded.store.
        val mergedView = LinkedHashMap<String, Any?>(RawConfigStore.jsonToRaw(configJson))
        mergedView["vault"] = mapOf(
            "version" to vault.version,
            "contents" to vault.contents,
            "keySalt" to vault.keySalt,
            "iv" to vault.iv,
        )
        mergedView["encrypted"] = true
        mergedView["configSync"] = mapOf("host" to "https://x", "configID" to 7L)
        val reloaded = RawConfigStore.loadRaw(RawConfigStore.dumpRaw(mergedView))
        assertEquals(
            setOf("version", "profiles", "groups", "ssh", "hotkeys", "appearance", "vault", "encrypted", "configSync"),
            reloaded.keys,
        )
        assertEquals(4, (reloaded["profiles"] as List<*>).size)
        assertEquals(4, RawConfigStore.toDomain(reloaded).profiles.size)
    }

    @Test
    fun `wrong passphrase on a desktop blob is BAD_DECRYPT`() {        val f = fixture()
        val s = f["stored"] as JsonObject
        fun str(o: JsonObject, k: String) = (o[k] as kotlinx.serialization.json.JsonPrimitive).content
        val vault = StoredVault(1, str(s, "contents"), str(s, "keySalt"), str(s, "iv"))
        try {
            VaultCrypto.decrypt(vault, "wrong-pass")
            fail("must throw")
        } catch (e: VaultCrypto.BadDecryptException) {
            // Expected.
        }
    }
}
